[2024-09-04 11:14:47,241] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:14:47] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:14:48,336] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:14:48,336] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:14:48] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:14:48,522] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:14:48,523] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:14:48] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:01,278] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:01] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:01,975] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:01] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:03,705] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:03] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:11,665] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:11] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:12,148] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:12] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:18:12,385] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:18:12] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:26,919] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:26] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:29,919] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:29] "OPTIONS /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:29,929] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:29,931] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:29] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:30,641] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:30,643] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:30] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:30,795] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:30,795] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:30] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:31,318] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:31,320] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:31] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:31,467] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:31,468] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:31] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:36,612] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:36] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:37,575] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:37] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:55,307] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:55] "OPTIONS /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:23:55,322] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:23:55,322] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:23:55] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:28:12,792] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:28:12] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:28:30,843] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:28:30] "OPTIONS /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:28:30,871] WARNING add_patient() L102  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L102 
[2024-09-04 11:28:30,872] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:28:30] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:29:43,583] INFO _log() L224   * Detected change in '/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py', reloading - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:32:31,265] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:32:31] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:32:39,551] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:32:39] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:03,397] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:03] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:15,347] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:15] "OPTIONS /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:15,404] WARNING add_patient() L100  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 11:34:15,404] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:15] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:41,153] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:41] "OPTIONS /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:41,178] WARNING add_patient() L100  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 11:34:41,179] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:41] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:43,168] WARNING add_patient() L100  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 11:34:43,169] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:43] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 11:34:43,332] WARNING add_patient() L100  Error adding patient 'Paula', Patient Paula already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 11:34:43,333] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 11:34:43] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
