[2024-09-04 12:51:18,870] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:18] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:22,527] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:22,527] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:22] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:22,536] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:22] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,347] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:23,348] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,360] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,722] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:23,723] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,728] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,904] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:23,904] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:23,912] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:23] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:24,080] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:24,080] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:24] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:24,086] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:24] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:25,890] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:51:25,890] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:25] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:51:25,897] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:51:25] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:52:21,050] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:52:21,051] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:52:21] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:52:21,059] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:52:21] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:52:21,565] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:52:21,565] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:52:21] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:52:21,571] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:52:21] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:21,671] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:55:21,673] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:21] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:21,680] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:21] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:22,161] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:55:22,162] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:22] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:22,170] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:22] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:22,381] WARNING add_patient() L100  Error adding patient 'Marcos', Patient Marcos already exists in the database - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L100 
[2024-09-04 12:55:22,381] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:22] "[31m[1mPOST /patient HTTP/1.1[0m" 409 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:22,389] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:22] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:55:34,834] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:55:34] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:56:11,343] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:56:11] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:56:41,664] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:56:41] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:56:46,878] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:56:46] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:56:47,459] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:56:47] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:58:25,175] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:58:25] "[31m[1mPOST /patient HTTP/1.1[0m" 422 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:58:25,197] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:58:25] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:58:26,277] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:58:26] "[31m[1mPOST /patient HTTP/1.1[0m" 422 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 12:58:26,285] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 12:58:26] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 13:02:53,596] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 13:02:53] "POST /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 13:02:53,602] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 13:02:53] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 13:02:53,608] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 13:02:53] "GET /patients HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
