[2024-09-04 10:36:10,264] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,271] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,279] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,342] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,343] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,343] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,471] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,492] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,501] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,526] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,527] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:10,535] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:10] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,253] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,290] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,291] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,292] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,444] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:36:13,522] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:36:13] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:37:56,314] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:37:56] "POST /patient HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:38:35,725] ERROR log_exception() L1449 Exception on /patients [GET] - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/cyberforming-1790/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py", line 51, in get_patients
    return represent_patient(patients), 200
  File "/home/cyberforming-1790/Documentos/mvp_sprint2/api/schemas/patient_schema.py", line 45, in represent_patient
    "id": patient.id,
AttributeError: 'list' object has no attribute 'id'
[2024-09-04 10:38:35,736] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:38:35] "[35m[1mGET /patients HTTP/1.1[0m" 500 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:38:57,316] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:38:57] "GET /patient?name=Paula HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:45:48,224] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:45:48] "DELETE /patient?name=Paula HTTP/1.1" 200 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:45:53,610] WARNING get_patient() L140  Error searching for patient 'Paula', Patient Paula not found in the database :/ - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L140 
[2024-09-04 10:45:53,611] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:45:53] "[33mGET /patient?name=Paula HTTP/1.1[0m" 404 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:45:55,497] WARNING get_patient() L140  Error searching for patient 'Paula', Patient Paula not found in the database :/ - call_trace=/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py L140 
[2024-09-04 10:45:55,498] INFO _log() L224  127.0.0.1 - - [04/Sep/2024 10:45:55] "[33mGET /patient?name=Paula HTTP/1.1[0m" 404 - - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2024-09-04 10:46:27,239] INFO _log() L224   * Detected change in '/home/cyberforming-1790/Documentos/mvp_sprint2/api/app.py', reloading - call_trace=/home/cyberforming-1790/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
